### ISSUE TITLE
Make organization invitation token validity configurable

### ISSUE THREAD

**Issue by gearnode** [getprobo/probo#41]
Make organization invitation token validity configurable via the configuration file.

```yaml
---
probod:
  auth:
    invation-confirmation-token-validity: 3600 // seconds
```
